# Generated by Django 3.0.6 on 2020-05-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_auto_20200522_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
