# Generated by Django 3.0.6 on 2020-05-23 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_remove_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.date(2020, 5, 23)),
        ),
    ]
